language: rust

matrix:
  include:
  - env: TARGET=x86_64-unknown-linux-gnu
  - env: CLIPPY=true
    os: linux
    rust: nightly
  allow_failures:
  - env: CLIPPY=true

install:
- if [ $CLIPPY ]; then cargo install clippy; cargo clippy; else cargo build; fi
script:
- cargo test
